- id: free
  available: true
  price: 0
  price_annual: 0
  price_package: 0
  credits: 100
  active: true
  next_plan: startup
  order: 1
- id: startup
  available: true
  price: 33.00
  price_annual: 356
  price_package: 31.50
  credits: 500
  active: true
  next_plan: pro
  order: 2
- id: pro
  available: true
  price: 117.50
  price_annual: 1269.00
  price_package: 104.00
  credits: 2000
  active: true
  next_plan: enterprise
  order: 3
- id: enterprise
  available: false
  price: 799.00
  price_annual: 8599.00
  price_package: 659.00
  credits: 15000
  active: false
  order: 4

# - id: "startup"
#   available: true
#   price: 33.00
#   annual_price: 356.40
#   queries_limit: 500
#   additional_package: true
#   additional_package_price: 31.50
#   licence: false
#   licences_limit: 0
#   additional_licence_price: 0  
#   terraform: true
#   key_value_store: true
#   branding_custom: false
#   active: true
#   user_limit: nil
#   next_plan: "pro"
#   order: 2
# - id: "pro"
#   available: true
#   price: 117.50
#   annual_price: 1269.00
#   queries_limit: 2000
#   additional_package: true
#   additional_package_price: 104.00
#   licence: false
#   licences_limit: 0
#   additional_licence_price: 0
#   terraform: true
#   key_value_store: true
#   branding_custom: true
#   active: true
#   user_limit: nil
#   next_plan: "enterprise"
#   order: 3
# - id: "enterprise"
#   available: false
#   price: 799.00
#   annual_price: 7990.00
#   queries_limit: 10000
#   additional_package: true
#   additional_package_price: 99.00
#   licence: true
#   licences_limit: 100
#   additional_licence_price: 499
#   terraform: true
#   key_value_store: true
#   branding_custom: true
#   active: true
#   user_limit: nil
#   order: 4
