name: "CI Pipeline"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  DATABASE_NAME: ${{ vars.DATABASE_NAME }}
  ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY }}
  ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY }}
  ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ${{ secrets.ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT }}
  RAILS_ENV: test
  MEILI_MASTER_KEY: password123
  DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432

jobs:
  scan_rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.6'
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop --parallel

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
      meilisearch:
        image: getmeili/meilisearch:v1.12
        env:
          MEILI_MASTER_KEY: password123
          MEILI_ENV: development
          MEILI_NO_ANALYTICS: "true"
        ports:
          - 7700:7700
        # On attend que Meilisearch réponde sur son endpoint de santé avant de lancer les tests
        options: >-
          --health-cmd="curl -f http://localhost:7700/health"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libpq-dev

      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.22'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Prepare tests
        working-directory: spec/dummy
        run: |
          bundle exec rails db:setup RAILS_ENV=test

      - name: Run tests
        run: |
          bundle exec rspec spec

